import { useState, useRef, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { useTheme } from '../../context/ThemeContext'
import { Button } from '../common/Button'

type AppNotification = {
  id: string
  title: string
  body: string
  time: string
  read: boolean
}

export const Navbar = () => {
  const { theme, toggleTheme } = useTheme()
  const { isAuthenticated, logout, currentUser } = useAuth()
  const navigate = useNavigate()

  // Notification states
  const [showNotifications, setShowNotifications] = useState(false)
  const [notifications, setNotifications] = useState<AppNotification[]>([
    {
      id: 'n1',
      title: 'Prompt Consensus Complete',
      body: 'Your visual learning prompt for "React Hooks" was generated by the AI Council.',
      time: '10m ago',
      read: false
    },
    {
      id: 'n2',
      title: 'Vision Analysis Successful',
      body: 'Mock OCR simulation extracted 28 lines from your uploaded snapshot.',
      time: '2h ago',
      read: false
    },
    {
      id: 'n3',
      title: 'Welcome to AIthera!',
      body: 'Start by generating a tailored guide in the AI Workspace.',
      time: '1d ago',
      read: true
    }
  ])

  const popoverRef = useRef<HTMLDivElement | null>(null)

  // Click outside to dismiss popover
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (popoverRef.current && !popoverRef.current.contains(event.target as Node)) {
        setShowNotifications(false)
      }
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
    }
  }, [])

  const unreadCount = notifications.filter(n => !n.read).length

  const handleMarkAllRead = () => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })))
  }

  const handleToggleRead = (id: string) => {
    setNotifications(prev =>
      prev.map(n => (n.id === id ? { ...n, read: !n.read } : n))
    )
  }

  const handleDeleteNotification = (id: string, e: React.MouseEvent) => {
    e.stopPropagation()
    setNotifications(prev => prev.filter(n => n.id !== id))
  }

  const handleLogout = async () => {
    await logout()
    navigate('/login', { replace: true })
  }

  return (
    <header className="navbar">
      <div className="brand-wrap">
        <div className="brand-mark">A</div>
        <div>
          <div className="brand">AIthera</div>
          <div className="brand-subtitle">Learning workspace</div>
        </div>
      </div>

      <div className="navbar-actions">
        <button
          type="button"
          className="icon-button"
          aria-label="Toggle theme"
          onClick={toggleTheme}
        >
          {theme === 'light' ? '🌙' : '☀️'}
        </button>

        {/* Notifications center bell container */}
        <div className="notifications-bell-shell" ref={popoverRef}>
          <button
            type="button"
            className={`icon-button bell-btn-interactive ${showNotifications ? 'active' : ''}`}
            aria-label={`Open notifications, ${unreadCount} unread`}
            onClick={() => setShowNotifications(!showNotifications)}
          >
            <span>🔔</span>
            {unreadCount > 0 && (
              <span className="bell-badge-count">{unreadCount}</span>
            )}
          </button>

          {/* Popover pane */}
          {showNotifications && (
            <div className="notifications-popover-tray animate-fade-in" role="dialog">
              <header className="popover-header">
                <h3>Notifications</h3>
                {unreadCount > 0 && (
                  <button
                    type="button"
                    className="mark-all-read-btn"
                    onClick={handleMarkAllRead}
                  >
                    Mark all as read
                  </button>
                )}
              </header>

              <div className="popover-body scrollable">
                {notifications.length > 0 ? (
                  <div className="notifications-list-group">
                    {notifications.map((n) => (
                      <div
                        key={n.id}
                        className={`notification-item-card ${n.read ? 'read-state' : 'unread-state'}`}
                        onClick={() => handleToggleRead(n.id)}
                      >
                        <div className="notification-card-header">
                          <strong className="notification-title">{n.title}</strong>
                          <button
                            type="button"
                            className="notification-dismiss-btn"
                            onClick={(e) => handleDeleteNotification(n.id, e)}
                            aria-label="Delete notification"
                          >
                            ×
                          </button>
                        </div>
                        <p className="notification-text-body">{n.body}</p>
                        <span className="notification-time-meta">⏱️ {n.time}</span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="notifications-empty-state">
                    <span className="empty-bell-icon">🔔</span>
                    <p className="muted text-xs">You're all caught up!</p>
                  </div>
                )}
              </div>
            </div>
          )}
        </div>

        <div className="avatar-pill" aria-label="Current user">
          <span className="avatar-dot">{(currentUser?.name || currentUser?.email || 'U').charAt(0).toUpperCase()}</span>
          <span className="avatar-label">{currentUser?.name || 'Learner'}</span>
        </div>
        {isAuthenticated ? (
          <Button type="button" variant="secondary" onClick={handleLogout}>Logout</Button>
        ) : null}
      </div>
    </header>
  )
}
export default Navbar
