"""Universal fields

Revision ID: 26d2de092d06
Revises: ec6f72770637
Create Date: 2026-07-31 07:30:33.031302+00:00

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '26d2de092d06'
down_revision = 'ec6f72770637'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###