"""add explanations table

Revision ID: ec6f72770637
Revises: 0282b94af7fe
Create Date: 2026-06-14 13:52:18.755209+00:00

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ec6f72770637'
down_revision = '0282b94af7fe'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consensus_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('final_prompt', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('consensus_reasoning', sa.Text(), nullable=True),
    sa.Column('combined_strengths', sa.JSON(), nullable=True),
    sa.Column('contributors', sa.JSON(), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['prompt_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consensus_results_request_id'), 'consensus_results', ['request_id'], unique=True)
    op.create_table('council_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['prompt_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_council_responses_request_id'), 'council_responses', ['request_id'], unique=False)
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['prompt_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('explanations')
    op.drop_index(op.f('ix_council_responses_request_id'), table_name='council_responses')
    op.drop_table('council_responses')
    op.drop_index(op.f('ix_consensus_results_request_id'), table_name='consensus_results')
    op.drop_table('consensus_results')
    # ### end Alembic commands ###