import json
import logging
from typing import Any, Dict, List, Optional
from src.models.council_response import CouncilResponse, ResponseMetadata, ResponseScore

# Configure logging
logger = logging.getLogger("aithera.response_normalizer")


class NormalizationError(Exception):
    """Exception raised when prompt response normalization fails."""
    pass


class ResponseNormalizer:
    """Normalizes raw model responses from various AI providers into standard CouncilResponse objects."""

    def __init__(self) -> None:
        """Initialize the ResponseNormalizer."""
        self._provider_default_roles = {
            "openai": "creator",
            "claude": "validator",
            "gemini": "refiner",
            "deepseek": "critic"
        }

    def _get_content_string(self, raw_response: Dict[str, Any], provider: str) -> str:
        """Extract the raw content string from the provider-specific response structure.

        Args:
            raw_response: The raw response dictionary from the AI provider.
            provider: The name of the AI provider.

        Returns:
            str: The raw content string from the provider response.

        Raises:
            NormalizationError: If the structure is malformed or unsupported.
        """
        provider_lower = provider.lower()
        try:
            if "openai" in provider_lower or "deepseek" in provider_lower:
                return raw_response["choices"][0]["message"]["content"]
            elif "claude" in provider_lower:
                content_item = raw_response["content"][0]
                if isinstance(content_item, dict):
                    return content_item["text"]
                return content_item
            elif "gemini" in provider_lower:
                return raw_response["candidates"][0]["content"]["parts"][0]["text"]
            else:
                raise NormalizationError(f"Unsupported provider: {provider}")
        except (KeyError, IndexError, TypeError) as e:
            logger.error("Failed to extract content string for provider %s: %s", provider, str(e))
            raise NormalizationError(
                f"Malformed raw response structure for provider '{provider}': {str(e)}"
            )

    def _parse_content_string(self, content_str: str) -> Dict[str, Any]:
        """Parse the content string, trying JSON parsing first, with regex/marker fallback.

        Args:
            content_str: The raw content string generated by the model.

        Returns:
            Dict[str, Any]: A dictionary containing prompt, reasoning, and strengths keys.
        """
        content_str = content_str.strip()
        # Strip markdown code fences if present
        if content_str.startswith("```json"):
            content_str = content_str[7:]
        elif content_str.startswith("```"):
            content_str = content_str[3:]
        if content_str.endswith("```"):
            content_str = content_str[:-3]
        content_str = content_str.strip()

        try:
            parsed = json.loads(content_str)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            logger.warning("Content string was not valid JSON. Falling back to plain text parsing.")

        # Fallback parsing for text content containing headings/labels
        prompt = content_str
        reasoning = "Generated by provider"
        strengths = ["Structured output"]

        content_lower = content_str.lower()
        if "reasoning:" in content_lower:
            parts = content_str.split("Reasoning:", 1)
            prompt = parts[0].strip()
            rest = parts[1].strip()
            if "strengths:" in rest.lower():
                sub_parts = rest.split("Strengths:", 1)
                reasoning = sub_parts[0].strip()
                strengths_text = sub_parts[1].strip()
                strengths = [
                    s.strip("- *").strip()
                    for s in strengths_text.split("\n")
                    if s.strip()
                ]
            else:
                reasoning = rest
        elif "strengths:" in content_lower:
            parts = content_str.split("Strengths:", 1)
            prompt = parts[0].strip()
            strengths_text = parts[1].strip()
            strengths = [
                s.strip("- *").strip()
                for s in strengths_text.split("\n")
                if s.strip()
            ]

        return {
            "prompt": prompt,
            "reasoning": reasoning,
            "strengths": strengths
        }

    def _parse_raw_content(self, raw_response: Dict[str, Any], provider: str) -> Dict[str, Any]:
        """Extract and parse content from raw response.

        Args:
            raw_response: The raw response dictionary.
            provider: The name of the provider.

        Returns:
            Dict[str, Any]: Extracted prompt details.
        """
        content_str = self._get_content_string(raw_response, provider)
        return self._parse_content_string(content_str)

    def extract_prompt(self, raw_response: Dict[str, Any], provider: str) -> str:
        """Extract the prompt content from the raw provider response.

        Args:
            raw_response: The raw response dictionary.
            provider: The provider name.

        Returns:
            str: The extracted prompt.

        Raises:
            NormalizationError: If prompt cannot be extracted.
        """
        parsed = self._parse_raw_content(raw_response, provider)
        prompt = parsed.get("prompt")
        if not prompt or not isinstance(prompt, str) or not prompt.strip():
            raise NormalizationError("Extracted prompt is empty or invalid.")
        return prompt.strip()

    def extract_reasoning(self, raw_response: Dict[str, Any], provider: str) -> str:
        """Extract the reasoning/rationale from the raw provider response.

        Args:
            raw_response: The raw response dictionary.
            provider: The provider name.

        Returns:
            str: The extracted reasoning.

        Raises:
            NormalizationError: If reasoning cannot be extracted.
        """
        parsed = self._parse_raw_content(raw_response, provider)
        reasoning = parsed.get("reasoning")
        if not reasoning or not isinstance(reasoning, str) or not reasoning.strip():
            raise NormalizationError("Extracted reasoning is empty or invalid.")
        return reasoning.strip()

    def extract_strengths(self, raw_response: Dict[str, Any], provider: str) -> List[str]:
        """Extract the strengths list from the raw provider response.

        Args:
            raw_response: The raw response dictionary.
            provider: The provider name.

        Returns:
            List[str]: The extracted strengths.

        Raises:
            NormalizationError: If strengths cannot be extracted.
        """
        parsed = self._parse_raw_content(raw_response, provider)
        strengths = parsed.get("strengths")
        if not strengths or not isinstance(strengths, list):
            raise NormalizationError("Extracted strengths is empty or invalid.")
        cleaned_strengths = [s.strip() for s in strengths if isinstance(s, str) and s.strip()]
        if not cleaned_strengths:
            raise NormalizationError("Extracted strengths list contains no valid strings.")
        return cleaned_strengths

    def extract_metadata(self, raw_response: Dict[str, Any], provider: str) -> Dict[str, Any]:
        """Extract metadata (token usage, response time, and model version) from raw response.

        Args:
            raw_response: The raw response dictionary.
            provider: The provider name.

        Returns:
            Dict[str, Any]: Dictionary containing extracted metadata keys.

        Raises:
            NormalizationError: If metadata extraction fails.
        """
        provider_lower = provider.lower()
        try:
            tokens_used = None
            response_time = raw_response.get("response_time")
            provider_version = None

            if "openai" in provider_lower or "deepseek" in provider_lower:
                usage = raw_response.get("usage", {})
                tokens_used = usage.get("total_tokens")
                provider_version = raw_response.get("model")
            elif "claude" in provider_lower:
                usage = raw_response.get("usage", {})
                if usage:
                    tokens_used = usage.get("input_tokens", 0) + usage.get("output_tokens", 0)
                provider_version = raw_response.get("model")
            elif "gemini" in provider_lower:
                usage = raw_response.get("usageMetadata", {})
                tokens_used = usage.get("totalTokenCount")
                provider_version = raw_response.get("modelVersion", "gemini")
            else:
                raise NormalizationError(f"Unsupported provider: {provider}")

            return {
                "tokens_used": tokens_used,
                "response_time": response_time,
                "provider_version": provider_version
            }
        except Exception as e:
            if isinstance(e, NormalizationError):
                raise
            raise NormalizationError(f"Failed to extract metadata for {provider}: {str(e)}")

    def _normalize_common(
        self,
        raw_response: Dict[str, Any],
        provider: str,
        role: Optional[str] = None
    ) -> CouncilResponse:
        """Shared logic for normalizing provider responses.

        Args:
            raw_response: The raw response dictionary.
            provider: The provider name.
            role: The role, falling back to provider defaults if None.

        Returns:
            CouncilResponse: The standard CouncilResponse.
        """
        if not role:
            role = self._provider_default_roles.get(provider.lower(), "creator")

        prompt = self.extract_prompt(raw_response, provider)
        reasoning = self.extract_reasoning(raw_response, provider)
        strengths = self.extract_strengths(raw_response, provider)
        meta_dict = self.extract_metadata(raw_response, provider)

        # Build ResponseMetadata
        metadata = ResponseMetadata(
            tokens_used=meta_dict.get("tokens_used"),
            response_time=meta_dict.get("response_time"),
            provider_version=meta_dict.get("provider_version")
        )

        # Build initial Score object (uncalculated)
        score = ResponseScore()

        # Build CouncilResponse using the Pydantic schema
        return CouncilResponse(
            model=meta_dict.get("provider_version") or provider,
            role=role,
            prompt=prompt,
            reasoning=reasoning,
            strengths=strengths,
            metadata=metadata,
            score=score
        )

    def normalize_openai_response(self, raw_response: Dict[str, Any], role: Optional[str] = None) -> CouncilResponse:
        """Normalize a raw OpenAI completions response into a CouncilResponse.

        Args:
            raw_response: The raw response dictionary.
            role: The assigned role.

        Returns:
            CouncilResponse: Standardized response object.
        """
        logger.info("Normalizing OpenAI response")
        return self._normalize_common(raw_response, "OpenAI", role)

    def normalize_claude_response(self, raw_response: Dict[str, Any], role: Optional[str] = None) -> CouncilResponse:
        """Normalize a raw Claude message response into a CouncilResponse.

        Args:
            raw_response: The raw response dictionary.
            role: The assigned role.

        Returns:
            CouncilResponse: Standardized response object.
        """
        logger.info("Normalizing Claude response")
        return self._normalize_common(raw_response, "Claude", role)

    def normalize_gemini_response(self, raw_response: Dict[str, Any], role: Optional[str] = None) -> CouncilResponse:
        """Normalize a raw Gemini response into a CouncilResponse.

        Args:
            raw_response: The raw response dictionary.
            role: The assigned role.

        Returns:
            CouncilResponse: Standardized response object.
        """
        logger.info("Normalizing Gemini response")
        return self._normalize_common(raw_response, "Gemini", role)

    def normalize_deepseek_response(self, raw_response: Dict[str, Any], role: Optional[str] = None) -> CouncilResponse:
        """Normalize a raw DeepSeek response into a CouncilResponse.

        Args:
            raw_response: The raw response dictionary.
            role: The assigned role.

        Returns:
            CouncilResponse: Standardized response object.
        """
        logger.info("Normalizing DeepSeek response")
        return self._normalize_common(raw_response, "DeepSeek", role)

    def normalize(self, provider_name: str, raw_response: Any, role: Optional[str] = None) -> CouncilResponse:
        """Universal dispatcher method to normalize any supported raw response.

        Args:
            provider_name: The name of the AI provider.
            raw_response: The raw response from the provider (expected Dict).
            role: The optional assigned role.

        Returns:
            CouncilResponse: Standardized response object.

        Raises:
            NormalizationError: If provider_name is unsupported or raw_response is invalid.
        """
        if not isinstance(raw_response, dict):
            raise NormalizationError("Raw response must be a dictionary.")

        provider_clean = provider_name.strip().lower()
        if "openai" in provider_clean:
            return self.normalize_openai_response(raw_response, role)
        elif "claude" in provider_clean:
            return self.normalize_claude_response(raw_response, role)
        elif "gemini" in provider_clean:
            return self.normalize_gemini_response(raw_response, role)
        elif "deepseek" in provider_clean:
            return self.normalize_deepseek_response(raw_response, role)
        else:
            raise NormalizationError(f"Unsupported AI provider: {provider_name}")
